### ISSUE TITLE
Is this a Chinese language pango designation-like repo?

### ISSUE THREAD

**Issue by corneliusroemer** [Memorablea/Memorable#16]
Just stumbled over this, is this where you gather lineage proposals similar to Pango designation but in Mandarin?

**Comment by Outpfmance** [comment]
@corneliusroemer Welcome to discover and come here. This is my Simplified Chinese knowledge base, focusing on the spread of COVID-19 in China. Including the CCDC weekly report data, the Chinese upload data in GISAID, and the Chinese internal website Genbase data, there will also be some noteworthy variants that pango has named and spread internationally.

**Comment by Memorablea** [comment]
> Just stumbled over this, is this where you gather lineage proposals similar to Pango designation but in Mandarin?

Welcome to discover and come here！

**Comment by Memorablea** [comment]
Thank you all for coming! Now, I will close this issue. @corneliusroemer 

If you have any more questions, please feel free to ask them in my repository or find us here. Finally, thank you again for coming!
